development:
  adapter: mysql2
  host: localhost
  database: zhangyu_blog
  username: root
  password: root
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  host: localhost
  database: zhangyu_blog_test
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: localhost
  username: root
  password: root
  database: zhangyu_blog_pro
  pool: 5
  timeout: 5000
