development:
  adapter: mysql2
  host: localhost
  database: ser_blog
  username: root
  password:
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  host: localhost
  database: ser_blog_test
  username: root
  password:
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: ser_blog_pro
  pool: 5
  timeout: 5000
